server:
  port: ${PORT:8080}

messages:
  home: Hello, rxx!

spring:
  application:
    name: Bootstrap Spring Boot
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8